const explanations = {
    growthMindset: `A growth mindset refers to the belief that abilities and intelligence can be developed through dedication, hard work, and continuous learning. Individuals with a growth mindset embrace challenges, persist in the face of setbacks, learn from criticism, and find lessons and inspiration in the success of others. This mindset fosters resilience, creativity, and a passion for learning, which are essential for personal and professional development.`,
    
    communicationAbility: `Effective communication is the foundation of successful interactions in both personal and professional settings. It involves not only speaking clearly and concisely but also actively listening and responding appropriately. Communication ability encompasses verbal and non-verbal communication, understanding and addressing the needs of the audience, and fostering an environment where open and honest dialogue is encouraged. Strong communication skills enhance teamwork, problem-solving, and leadership effectiveness.`,
    
    humanResourcesManagement: `Human resources management involves overseeing the recruitment, development, and well-being of an organization's employees. It includes tasks such as hiring, training, performance evaluation, conflict resolution, and ensuring compliance with labor laws. Effective HR management fosters a positive work environment, promotes employee engagement, and aligns the workforce with the organization's strategic goals. By understanding and addressing employees' needs and strengths, HR professionals can enhance productivity and job satisfaction.`,
    
    decisionMaking: `Decision-making is the process of identifying and choosing among various options based on the desired outcomes. Effective decision-making involves gathering relevant information, assessing alternatives, considering potential consequences, and selecting the most appropriate course of action. It requires critical thinking, analytical skills, and sometimes the ability to make decisions under pressure. Good decision-making can lead to better problem-solving, resource management, and overall success in achieving organizational and personal goals.`,
    
    problemSolvingAbility: `Problem-solving is the ability to identify, analyze, and resolve issues in a timely and efficient manner. It involves understanding the root causes of a problem, generating potential solutions, evaluating their feasibility, and implementing the best course of action. Strong problem-solving skills are essential for overcoming obstacles, adapting to changing circumstances, and achieving objectives. Effective problem-solvers are often proactive, resourceful, and able to think creatively to find innovative solutions.`,
    
    leadershipHumanistic: `Humanistic leadership emphasizes respect, empathy, and ethical behavior in guiding and motivating others. Leaders with this style prioritize the well-being and development of their team members, foster positive relationships, and create an inclusive and supportive environment. They lead by example, show genuine concern for others, and encourage open communication and collaboration. Humanistic leaders inspire loyalty and trust, and their approach can lead to higher levels of employee satisfaction and performance.`,
    
    leadershipOrganizational: `Organizational leadership focuses on creating and maintaining effective systems and structures to achieve strategic goals. This type of leadership involves setting clear objectives, developing policies and procedures, and ensuring that resources are allocated efficiently. Organizational leaders excel in planning, coordinating, and monitoring activities to ensure that the organization operates smoothly and effectively. They prioritize consistency, accountability, and continuous improvement to drive long-term success and stability.`,
  };
  
  export default explanations;
  