# Generated by Django 4.2.13 on 2024-06-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="M", max_length=200),
        ),
    ]
