# Generated by Django 4.2.13 on 2024-06-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="None", max_length=200),
        ),
    ]
