# Generated by Django 4.2.10 on 2024-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedsurvey',
            name='access_token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
